"use client";
import { useEffect, useRef, useState } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { Download, Upload, Route, Check, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { blankReview, hasReviewChanges, mergeReviewLabels, parseReviewExport, reviewImportConflicts, reviewNodes, type ReviewCase, type ReviewDraft, type ReviewExport, type ReviewLabel } from "@/lib/review";
const ReviewMap = dynamic(() => import("@/components/review-map"), { ssr: false });
const decisions: Record<ReviewLabel["associationType"], string> = { segment: "Supported street segment", intersection: "Supported intersection context", ambiguous: "Ambiguous location", insufficient_location: "Insufficient location evidence", outside_scope: "Outside audit scope" };
export default function ReviewWorkbench() {
  const [cases, setCases] = useState<ReviewCase[]>([]), [hashes, setHashes] = useState<Record<string, string>>({});
  const [loadError, setLoadError] = useState(""), [notice, setNotice] = useState(""), [attempt, setAttempt] = useState(0), [position, setPosition] = useState(0);
  const [reviewer, setReviewer] = useState(""), [labels, setLabels] = useState<Record<string, ReviewLabel>>({}), [drafts, setDrafts] = useState<Record<string, ReviewDraft>>({});
  const [exported, setExported] = useState<Record<string, ReviewLabel>>({}), [exportDialog, setExportDialog] = useState(false), [pendingImport, setPendingImport] = useState<ReviewExport | null>(null), [jump, setJump] = useState(""), [importing, setImporting] = useState(false);
  const importFile = useRef<HTMLInputElement>(null);
  useEffect(() => {
    const controller = new AbortController(); setLoadError("");
    Promise.all(["/quality/cases.json", "/quality/report.json"].map(async url => { const response = await fetch(url, { signal: controller.signal }); if (!response.ok) throw new Error("Review materials could not load."); return response.json(); })).then(results => { const items = results[0] as ReviewCase[], report = results[1] as { hashes: Record<string, string> }; if (!Array.isArray(items) || !items.length || !report.hashes) throw new Error("Invalid review materials."); setCases(items); setHashes(report.hashes); }).catch(e => { if (!controller.signal.aborted) setLoadError(e instanceof Error ? e.message : "Review materials could not load."); });
    return () => controller.abort();
  }, [attempt]);
  const item = cases[position], draft = item ? drafts[item.id] || labels[item.id] || blankReview() : blankReview(), nodes = item ? reviewNodes(item) : [];
  const completed = Object.keys(labels).length, draftCount = Object.entries(drafts).filter(([id, value]) => hasReviewChanges(value, labels[id])).length;
  const dirty = item && hasReviewChanges(drafts[item.id], labels[item.id]);
  const unexported = Object.entries(labels).some(([id, label]) => JSON.stringify(label) !== JSON.stringify(exported[id]));
  useEffect(() => { if (!draftCount && !unexported) return; const guard = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", guard); return () => window.removeEventListener("beforeunload", guard); }, [draftCount, unexported]);
  function change(patch: Partial<ReviewDraft>) { if (item) setDrafts(previous => ({ ...previous, [item.id]: { ...draft, ...patch } })); }
  function toggle(kind: "acceptableSegmentIds" | "acceptableNodeIds", id: string) { change({ [kind]: draft[kind].includes(id) ? draft[kind].filter(value => value !== id) : [...draft[kind], id] }); }
  function discard() { if (item) setDrafts(previous => { const next = { ...previous }; delete next[item.id]; return next; }); }
  const valid = !!draft.associationType && [...draft.rationale.trim()].length >= 10 && [...draft.rationale].length <= 10000 && (draft.associationType !== "segment" || !!draft.acceptableSegmentIds.length) && (draft.associationType !== "intersection" || !!draft.acceptableNodeIds.length);
  function save() {
    if (!item || !valid || !draft.associationType || !reviewer.trim() || !dirty) return;
    const label: ReviewLabel = { ...draft, associationType: draft.associationType, rationale: draft.rationale.trim(), reviewedAt: new Date().toISOString() };
    try { parseReviewExport({ schemaVersion: 1, reviewerId: reviewer, hashes, labels: { [item.id]: label } }, cases, hashes); setLabels(previous => ({ ...previous, [item.id]: label })); discard(); setNotice(`Decision for collision ${item.id} recorded. Export to keep it.`); }
    catch (error) { setNotice(error instanceof Error ? error.message : "Unable to record this decision."); }
  }
  function navigate(next: number) { if (next >= 0 && next < cases.length) { setPosition(next); setNotice(""); } }
  function nextUnrecorded() { for (let offset = 1; offset <= cases.length; offset++) { const next = (position + offset) % cases.length; if (!labels[cases[next].id]) { navigate(next); return; } } setNotice("Every case has a recorded decision. Export your review."); }
  function findCase(event: React.FormEvent) { event.preventDefault(); const query = jump.trim(), exact = cases.findIndex(candidate => candidate.id === query), ordinal = /^\d+$/.test(query) ? Number(query) - 1 : -1; if (exact >= 0) navigate(exact); else if (ordinal >= 0 && ordinal < cases.length) navigate(ordinal); else setNotice("Enter a case number from 1 to " + cases.length + " or a collision ID in this packet."); }
  function download() {
    const packet = parseReviewExport({ schemaVersion: 1, reviewerId: reviewer, hashes, labels }, cases, hashes);
    const blob = new Blob([JSON.stringify(packet, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob), link = document.createElement("a"); link.href = url; link.download = "veripath-review-" + reviewer.replace(/[^a-zA-Z0-9_-]/g, "_") + ".json"; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); setExported({ ...labels }); setExportDialog(false); setNotice("Download requested. Keep the JSON file to resume this review.");
  }
  function applyImport(packet: ReviewExport, strategy: "reject" | "keep" | "replace") { const merged = mergeReviewLabels(labels, packet.labels, strategy); setLabels(merged); setReviewer(completed ? reviewer : packet.reviewerId); setExported(previous => ({ ...previous, ...Object.fromEntries(Object.entries(packet.labels).filter(([id, label]) => JSON.stringify(merged[id]) === JSON.stringify(label))) })); setPendingImport(null); const count = Object.keys(packet.labels).length; setNotice(`Imported ${count} validated ${count === 1 ? "decision" : "decisions"}. Review times were preserved.`); }
  async function importReview(file: File | undefined) {
    if (!file) return;
    setImporting(true);
    try { if (draftCount) throw new Error("Record or discard your drafts before importing."); if (file.size > 5 * 1024 * 1024) throw new Error("Choose a review export smaller than 5 MB."); const packet = parseReviewExport(JSON.parse(await file.text()), cases, hashes, reviewer); if (reviewImportConflicts(labels, packet.labels).length) setPendingImport(packet); else applyImport(packet, "reject"); }
    catch (error) { setNotice(error instanceof Error ? error.message : "This review file could not be read."); }
    finally { setImporting(false); if (importFile.current) importFile.current.value = ""; }
  }
  const status = dirty ? "Unsaved draft" : item && labels[item.id] ? JSON.stringify(labels[item.id]) === JSON.stringify(exported[item.id]) ? "Exported decision" : "Recorded · needs export" : "Unreviewed";
  return <main className="quality-page review-page"><nav className="quality-nav"><Link className="brand" href="/"><span className="brand-symbol"><Route size={23}/></span>VeriPath<span className="brand-period">.</span></Link><Link href="/quality">Evidence quality</Link></nav>
    <div className="review-heading"><div><div className="eyebrow">INDEPENDENT LOCATION REVIEW</div><h1>Review the source evidence.</h1><p>Coordinates, street names and raw road context. Matcher decisions are hidden.</p></div><div className="review-progress"><b>{completed}<span> / {cases.length || 260}</span></b><span>decisions recorded</span>{draftCount > 0 && <small>{draftCount} unsaved {draftCount === 1 ? "draft" : "drafts"}</small>}</div></div>
    <div className="review-toolbar"><label>Reviewer code<Input placeholder="e.g. reviewer-a" value={reviewer} disabled={completed > 0 || importing} onChange={e => setReviewer(e.target.value)} maxLength={80}/></label><div className="review-file-actions"><input ref={importFile} type="file" accept=".json,application/json" className="sr-only" aria-label="Import a review export" onChange={e => void importReview(e.target.files?.[0])}/><Button variant="outline" onClick={() => importFile.current?.click()} disabled={!cases.length || draftCount > 0 || importing} title={draftCount ? "Record or discard drafts before importing" : "Resume an exported review"}><Upload size={16}/>Import review</Button><Button variant="outline" onClick={() => draftCount ? setExportDialog(true) : download()} disabled={!reviewer.trim() || !completed || importing}><Download size={16}/>Export decisions</Button></div></div>
    <p className="quality-note">Drafts survive case changes in this tab. Export recorded decisions before leaving or refreshing; import your JSON to resume. Decisions are not uploaded. Reviewer codes stay fixed once a decision is recorded.</p>
    <Accordion type="single" collapsible className="review-guidance"><AccordionItem value="guide"><AccordionTrigger>How to assess a case</AccordionTrigger><AccordionContent>
      <p>Review this ground-level NYC study independently. Avoid matcher results, source code and another reviewer’s decisions while completing your own assessment.</p>
      <dl><div><dt>Supported street segment</dt><dd>The source supports street-segment context. Select every independently acceptable segment ID.</dd></div><div><dt>Supported intersection context</dt><dd>The source supports a physical ground-level junction. Select every independently acceptable shared-node ID.</dd></div><div><dt>Ambiguous location</dt><dd>Credible evidence points to competing possibilities that the report cannot distinguish.</dd></div><div><dt>Insufficient location evidence</dt><dd>Missing or unusable evidence prevents a defensible association.</dd></div><div><dt>Outside audit scope</dt><dd>The evidence clearly places the report outside this ground-level study or its geographic area.</dd></div></dl>
      <p>Select multiple IDs only when each is supported. A nearest cross street, line crossing or purple node alone does not establish intersection involvement. Raw levels include ground, non-ground and unknown context; MM is the source’s ground-level code. Current geometry may differ from the report date.</p>
      <p>Explain supporting evidence and uncertainty, record each decision, then export your JSON. Drafts survive case navigation, but are not included in exports and do not survive a reload or closed tab.</p>
      <p>Two human reviewers must finish independently. A third reviewer resolves cases where their assessment or selected ID sets differ. Incomplete cases remain pending; agreement does not verify the physical collision location.</p>
    </AccordionContent></AccordionItem></Accordion>
    {notice && <div className="review-notice" role="status">{notice}</div>}
    {loadError ? <div className="error-state" role="alert">{loadError}<Button variant="outline" onClick={() => setAttempt(n => n + 1)}>Retry</Button></div> : !item ? <p role="status">Loading frozen review material…</p> : <>
      <div className="case-navigation"><div><Button variant="outline" onClick={() => navigate(position - 1)} disabled={!position}>Previous</Button><span>Case {position + 1} / {cases.length}</span><Button variant="outline" onClick={() => navigate(position + 1)} disabled={position === cases.length - 1}>Next</Button><Button variant="ghost" onClick={nextUnrecorded}>Next unrecorded</Button></div><form onSubmit={findCase}><Input aria-label="Case number or collision ID" placeholder="Case number or collision ID" value={jump} onChange={e => setJump(e.target.value)}/><Button type="submit" size="icon" variant="outline" aria-label="Find case"><Search size={16}/></Button></form></div>
      <div className="review-grid"><section><div className="review-source"><h2>Collision report {item.id}</h2><dl><div><dt>Date / borough</dt><dd>{item.date} · {item.borough}</dd></div><div><dt>Reported collision street</dt><dd>{item.onStreet || "Not reported"}</dd></div><div><dt>Nearest cross street</dt><dd>{item.nearestCrossStreet || "Not reported"}</dd></div><div><dt>Address / location text</dt><dd>{item.locationText || "Not reported"}</dd></div><div><dt>Coordinates</dt><dd>{item.coordinate ? item.coordinate.map(n => n.toFixed(6)).join(", ") + " (longitude, latitude)" : "Missing"}</dd></div><div><dt>Injury / fatality modes</dt><dd>{item.modes.join(", ") || "Not specified"}</dd></div></dl></div><ReviewMap item={item} segments={draft.acceptableSegmentIds} nodes={draft.acceptableNodeIds}/><p className="quality-note">Red: report coordinates. Grey: roads. Purple: raw shared nodes, including elevated and unknown levels. The nearest cross street does not establish intersection involvement.</p></section>
      <fieldset className="review-decision" disabled={importing} aria-labelledby="assessment-title"><div className="review-decision-heading"><h2 id="assessment-title">Your assessment</h2><span className={dirty ? "draft-status" : "saved-status"}>{status}</span></div><label htmlFor="review-type">Association type</label><NativeSelect id="review-type" value={draft.associationType} onChange={e => change({ associationType: e.target.value as ReviewDraft["associationType"], acceptableSegmentIds: [], acceptableNodeIds: [] })}><NativeSelectOption value="">Choose an assessment</NativeSelectOption>{Object.entries(decisions).map(([key, label]) => <NativeSelectOption key={key} value={key}>{label}</NativeSelectOption>)}</NativeSelect>
      {draft.associationType === "segment" && <fieldset className="review-candidates"><legend>Acceptable source segments</legend><p>Select every segment supported by the report.</p><div>{item.roads.map(road => <label key={road.id}><input type="checkbox" checked={draft.acceptableSegmentIds.includes(road.id)} onChange={() => toggle("acceptableSegmentIds", road.id)}/><span>{road.street || "Unnamed road"}<small>{road.id} · level {road.levels || "unknown"}</small></span></label>)}</div></fieldset>}
      {draft.associationType === "intersection" && <fieldset className="review-candidates"><legend>Acceptable shared nodes</legend><p>Select every node supported by the report.</p><div>{nodes.length ? nodes.map(node => <label key={node.id}><input type="checkbox" checked={draft.acceptableNodeIds.includes(node.id)} onChange={() => toggle("acceptableNodeIds", node.id)}/><span>Node {node.id}<small>{node.roads.length} nearby source segments</small></span></label>) : <p>No shared source nodes in this case.</p>}</div></fieldset>}
      <label htmlFor="review-rationale">Evidence and uncertainty</label><Textarea id="review-rationale" value={draft.rationale} maxLength={10000} onChange={e => change({ rationale: e.target.value })} placeholder="Explain what supports your assessment. Note conflicting evidence." rows={4}/><p className="quality-note">At least 10 characters. Choose ambiguity if the report cannot distinguish nearby locations.</p><Button className="quality-save" onClick={save} disabled={!valid || !reviewer.trim() || !dirty}><Check size={16}/>Record decision</Button>{!reviewer.trim() && <p className="quality-note">Enter your reviewer code to record a decision.</p>}{dirty && <Button variant="ghost" className="review-discard" onClick={discard}>Discard draft changes</Button>}<p className="quality-note">No assessment is preselected. This review does not certify route safety. Independent agreement or adjudication is still required.</p></fieldset></div>
    </>}
    <Dialog open={!!pendingImport} onOpenChange={open => { if (!open) setPendingImport(null); }}><DialogContent><DialogHeader><DialogTitle>Some decisions differ.</DialogTitle><DialogDescription>{pendingImport ? reviewImportConflicts(labels, pendingImport.labels).length : 0} imported {pendingImport && reviewImportConflicts(labels, pendingImport.labels).length === 1 ? "decision conflicts" : "decisions conflict"} with this session. Choose which copy to keep for those cases. New cases will be added.</DialogDescription></DialogHeader><div className="review-dialog-actions"><Button variant="outline" onClick={() => setPendingImport(null)}>Cancel import</Button><Button variant="outline" onClick={() => pendingImport && applyImport(pendingImport, "keep")}>Keep session decisions</Button><Button onClick={() => pendingImport && applyImport(pendingImport, "replace")}>Use imported decisions</Button></div></DialogContent></Dialog>
    <Dialog open={exportDialog} onOpenChange={setExportDialog}><DialogContent><DialogHeader><DialogTitle>Export recorded decisions?</DialogTitle><DialogDescription>{draftCount} unsaved {draftCount === 1 ? "draft" : "drafts"} will remain in this tab. The file will contain only your {completed} recorded {completed === 1 ? "decision" : "decisions"}.</DialogDescription></DialogHeader><div className="review-dialog-actions"><Button variant="outline" onClick={() => setExportDialog(false)}>Keep reviewing</Button><Button onClick={download}>Export recorded decisions</Button></div></DialogContent></Dialog>
  </main>;
}
