import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Route } from "lucide-react";
import report from "@/public/quality/report.json";
import reasonLabels from "@/lib/matching-reasons.json";

export const metadata = { title: "Evidence quality · VeriPath" };
const number = (n: number) => n.toLocaleString("en-US");
const labels: Record<string, string> = { strong: "Street segment", intersection: "Intersection context", ambiguous: "Ambiguous · withheld", unmatched: "No nearby road", missing_coordinates: "Missing coordinates", outside_bounding_area: "Outside audit bounds" };
export default function QualityPage() {
  const associated = report.counts.strong + report.counts.intersection;
  return <main className="quality-page">
    <nav className="quality-nav"><Link className="brand" href="/"><span className="brand-symbol"><Route size={23}/></span>VeriPath<span className="brand-period">.</span></Link><Link href="/"><ArrowLeft size={16}/>Route explorer</Link></nav>
    <div className="eyebrow">NYC EVIDENCE AUDIT · {report.snapshotWindow}</div><h1>Coverage, with<br/><span>uncertainty in view.</span></h1>
    <p className="quality-lead">Where can we associate a collision report with a road? This audit accounts for all {number(report.records)} injury and fatality reports in the snapshot. Association coverage does not measure accuracy.</p>
    <div className="quality-stats"><article><span>Association coverage</span><b>{(associated / report.records * 100).toFixed(1)}%</b><p>{number(associated)} street or node associations</p></article><article><span>Independent review</span><b>0 / 260</b><p>200 representative + 60 challenge cases</p></article><article><span>Matching accuracy</span><b className="stat-text">Not evaluated</b><p>Awaiting independent labels and adjudication</p></article></div>
    <section className="quality-section"><h2>Every report has a place in the denominator.</h2><div className="coverage-bars">{Object.entries(report.counts).map(([key, value]) => <div key={key}><div><span>{labels[key]}</span><b>{number(value)} <small>{(value / report.records * 100).toFixed(1)}%</small></b></div><div className="coverage-track"><i style={{ width: `${value / report.records * 100}%` }} className={key === "strong" || key === "intersection" ? "associated" : "withheld"}/></div></div>)}</div></section>
    <section className="quality-section"><h2>Why assignments were withheld</h2><p>Each withheld report has one primary reason. More than one rule may fail; the first failing rule determines this breakdown.</p><div className="quality-table-wrap"><table className="quality-table reason-table"><thead><tr><th>Primary reason</th><th>Reports</th><th>Share of withheld reports</th></tr></thead><tbody>{Object.entries(report.withheldReasons).sort(([,a],[,b])=>b-a).map(([code,count])=><tr key={code}><th>{reasonLabels[code as keyof typeof reasonLabels]}</th><td>{number(count)}</td><td>{(count/(report.records-associated)*100).toFixed(1)}%</td></tr>)}</tbody></table></div><p className="quality-note">These reasons explain a rule’s decision. They are not calibrated confidence or evidence that an accepted association is correct. {report.assignmentRegression?.comparedRecords.toLocaleString()} coordinate-eligible assignments were compared with the preceding release; none changed.</p></section>
    <section className="quality-section"><h2>Coverage across boroughs</h2><div className="quality-table-wrap"><table className="quality-table"><thead><tr><th>Borough</th><th>Reports</th><th>Street</th><th>Intersection</th><th>Withheld / missing</th></tr></thead><tbody>{Object.entries(report.byBorough).sort(([a], [b]) => a.localeCompare(b)).map(([borough, counts]) => { const total = Object.values(counts).reduce((a, b) => a + b, 0); return <tr key={borough}><th>{borough === "Unknown" ? "Not reported" : borough.toLowerCase().replace(/\b\w/g, s => s.toUpperCase())}</th><td>{number(total)}</td><td>{number(counts.strong)}</td><td>{number(counts.intersection)}</td><td>{number(total - counts.strong - counts.intersection)}</td></tr>; })}</tbody></table></div><p className="quality-note">Unknown boroughs stay visible. Travel-mode groups overlap; each collision counts once overall.</p></section>
    <section className="review-callout"><div><div className="eyebrow">NEXT: INDEPENDENT REVIEW</div><h2>A map, the source report,<br/>and your judgment.</h2><p>Reviewers see raw road and node context with matcher decisions hidden. Separate reviewers must resolve disagreements before correctness metrics are published.</p></div><Link className="quality-action" href="/review">Open review workspace<ArrowUpRight size={18}/></Link></section>
    <section className="quality-section"><h2>What an intersection association means</h2><p>Both reported street names must agree with distinct road families at a shared, ground-level node. Coordinates must be within 15 metres, with at least a 10-metre margin over the next named candidate. Shared endpoints must agree within 3 metres. A route can show this context when strong matches establish connected approach and exit branches, and its geometry passes within 12 metres of the node.</p><p>The source’s nearest cross street alone does not establish intersection involvement. A node association cannot identify an approach, turn, responsibility or the risk of your trip. These initial rules still need review.</p></section>
    <section className="quality-section"><h2>Limits we keep visible</h2><ul>{report.limitations.map(limit => <li key={limit}>{limit}</li>)}</ul><p>Forecasts remain disabled. The previously examined 2025 model audit is separate from this matching audit; a future temporal test must be frozen before its outcomes are opened.</p><div className="quality-links"><a href="/quality/report.json">Download coverage report<ArrowUpRight size={15}/></a><a href="/model/validation.json">Model validation audit<ArrowUpRight size={15}/></a><a href={report.sources.crashes} target="_blank" rel="noopener noreferrer">NYC collision source<ArrowUpRight size={15}/></a></div></section>
  </main>;
}
